import type { Metadata } from "next";
import { Cinzel_Decorative } from "next/font/google";
import "./globals.css";
import Header from "../components/header";

const cinzelDecorative = Cinzel_Decorative({
  subsets: ["latin"],
  weight: ["400", "700", "900"],
  display: "swap",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${cinzelDecorative.className} antialiased`}>
        < Header />
        {children}
      </body>
    </html>
  );
}
